# This is a basic workflow to help you get started with Actions

name: Github-Profile-Summary-Cards

# Controls when the workflow will run
on:
  schedule:
    # Triggers every 24 hours
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Import the target action: `release` branch in vn7n24fzkq/github-profile-summary-cards repository
      - run: |
          git config --global user.name=hbx
          git config --global user.email=3157726199@qq.com
          git commit --allow-empty -m ""
          git push
    
        
        
        
